### ISSUE TITLE
stylesIn > Merging throw Unhandled 'error'

### ISSUE THREAD

**Issue by yekz** [laravel/elixir#150]
elixir version 2.10

```sh
[10:54:32] Finished 'less' after 7.77 s
[10:54:32] Starting 'styles'...
[10:54:32] Merging: public/css/**/*.css

events.js:85
      throw er; // Unhandled 'error' event
            ^
SyntaxError: /Users/kezhong/wwwroot/shipit/laravel-pro/tmp/public/css/all.css: Unexpected token (9:5)
   7 | /* Bootstrap Framework */
   8 | /*! normalize.css v3.0.2 | MIT License | git.io/normalize */
>  9 | body {
     |      ^
  10 |   margin: 0;
  11 | }
  12 | article,
    at Parser.pp.raise (/Users/kezhong/wwwroot/shipit/laravel-pro/tmp/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/location.js:73:13)
    at Parser.pp.unexpected (/Users/kezhong/wwwroot/shipit/laravel-pro/tmp/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/parseutil.js:87:8)
    at Parser.pp.semicolon (/Users/kezhong/wwwroot/shipit/laravel-pro/tmp/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/parseutil.js:66:73)
    at Parser.pp.parseExpressionStatement (/Users/kezhong/wwwroot/shipit/laravel-pro/tmp/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/statement.js:372:8)
    at Parser.parseExpressionStatement (/Users/kezhong/wwwroot/shipit/laravel-pro/tmp/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/plugins/flow.js:657:20)
    at Parser.pp.parseStatement (/Users/kezhong/wwwroot/shipit/laravel-pro/tmp/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/statement.js:119:188)
    at Parser.parseStatement (/Users/kezhong/wwwroot/shipit/laravel-pro/tmp/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/plugins/flow.js:636:22)
    at Parser.pp.parseTopLevel (/Users/kezhong/wwwroot/shipit/laravel-pro/tmp/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/statement.js:22:21)
    at Object.parse (/Users/kezhong/wwwroot/shipit/laravel-pro/tmp/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/index.js:106:12)
    at exports.default (/Users/kezhong/wwwroot/shipit/laravel-pro/tmp/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/lib/babel/helpers/parse.js:47:19)

```

**Comment by yekz** [comment]
I did this:
```js
mix.less(['app.less']).stylesIn('public/css', 'public/css');
```

**Comment by zgldh** [comment]
Same issue

**Comment by JeffreyWay** [comment]
Fixed.
