### ISSUE TITLE
Note: The code generator has deoptimised the styling of "..." as it exceeds the max of "100KB".

### ISSUE THREAD

**Issue by vanntian** [laravel/elixir#153]
a few days ago,i created a project with 5.1,it's well.this is new project, i suspect this is a bug.
gulpfile:
```javascript
elixir(function (mix) {
    mix.scripts([
        'angular/angular.min.js',
        'angular-animate/angular-animate.min.js',
        'angular-aria/angular-aria.min.js',
        'angular-material/angular-material.min.js'
    ], 'resources/assets/js/lib.js', 'resources/assets/lib');
});
}
```
console :
Starting 'scripts'...
[10:26:55] Merging: resources/assets/lib/angular/angular.min.js, resources/assets/lib/angular-animate/angular-animate.min.js, resources/assets/lib/angular-aria/angular-aria.min.js, resources/assets/lib/angular-material/angular-material.min.js
[BABEL] Note: The code generator has deoptimised the styling of ".../resources/assets/lib/angular/lib.js" as it exceeds the max of "100KB".
[10:27:02] Finished 'scripts' after 7.43 s
![qq 20150528103609](https://cloud.githubusercontent.com/assets/10600430/7851637/880d0252-0525-11e5-9cf0-8c77bfdf55fa.png)

**Comment by Cerberize** [comment]
Solution for now from killtw.

add a file in your root folder and name it "elixir.json"
```
{
    "babel": {
        "enable": true,
        "options": {
            "stage": 2,
            "query": {
                "compact": false
            }
        }
    }
}
```
Source: https://laracasts.com/discuss/channels/elixir/cant-compile-scripts

**Comment by killtw** [comment]
It is related to `compact` option of Babel, default value is `auto`.
You can see all options in [Babel documentation](https://babeljs.io/docs/usage/options/)

**Comment by vanntian** [comment]
@Cerberize thanks @killtw 叼,我换到1.x了

**Comment by acharkizakaria** [comment]
Trying to add query in "elixir.json" :

```
"query": {
            "compact": false
   }
```

I got this message Error : 

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
ReferenceError: [BABEL] Planning_base\resources\assets\js\libs\all.js: Unknown option: query
    at Logger.error (Planning_base\node_modules\laravel-elixir\node_modules\gulp-babel\node_modules\babel-core\lib\babel\transformation\file\logger.js:33:11)
    at File.normalizeOptions (Planning_base\node_modules\laravel-elixir\node_modules\gulp-babel\node_modules\babel-core\lib\babel\transformation\file\index.js:166:
29)
    at new File (Planning_base\node_modules\laravel-elixir\node_modules\gulp-babel\node_modules\babel-core\lib\babel\transformation\file\index.js:145:22)
    at TransformerPipeline.transform (Planning_base\node_modules\laravel-elixir\node_modules\gulp-babel\node_modules\babel-core\lib\babel\transformation\transforme
r-pipeline.js:87:16)
    at DestroyableTransform._transform (Planning_base\node_modules\laravel-elixir\node_modules\gulp-babel\index.js:30:20)
    at DestroyableTransform.Transform._read (Planning_base\node_modules\laravel-elixir\node_modules\gulp-babel\node_modules\through2\node_modules\readable-stream\l
ib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (Planning_base\node_modules\laravel-elixir\node_modules\gulp-babel\node_modules\through2\node_modules\readable-stream\
lib\_stream_transform.js:172:12)
    at doWrite (Planning_base\node_modules\laravel-elixir\node_modules\gulp-babel\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10
)
    at writeOrBuffer (Planning_base\node_modules\laravel-elixir\node_modules\gulp-babel\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:
227:5)
    at DestroyableTransform.Writable.write (Planning_base\node_modules\laravel-elixir\node_modules\gulp-babel\node_modules\through2\node_modules\readable-stream\li
b\_stream_writable.js:194:11)
```

**Comment by cd-rum** [comment]
None of those worked for me, but throwing the `compact: false` line into brunch-config did the trick:
```
// Configure your plugins
  plugins: {
    babel: {
      // Do not use ES6 compiler in vendor code
      ignore: [/web\/static\/vendor/],
      compact: false
    }
  }
```

**Comment by aocneanu** [comment]
@cd-rum could you point me to this file? I also have this error. Thanks

**Comment by IsuruDilhan** [comment]
In react/redux/webpack/babel build fixed this error by removing script tag type text/babel

`<script type="text/babel" src="/js/bundle.js"></script>`

Into
`<script src="/js/bundle.js"></script>`
