### ISSUE TITLE
Error: watch EMFILE

### ISSUE THREAD

**Issue by affinitycloud** [laravel/elixir#156]
Getting this when running 'gulp watch --production' or 'gulp watch'.

2015-05-28 14:26 gulp[18756] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-05-28 14:26 gulp[18756] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-05-28 14:26 gulp[18756] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-05-28 14:26 gulp[18756] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
[14:26:12] Finished 'watch-assets' after 17 ms
2015-05-28 14:26 gulp[18756] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-05-28 14:26 gulp[18756] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-05-28 14:26 gulp[18756] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: watch EMFILE
    at exports._errnoException (util.js:746:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1157:26)

**Comment by JeffreyWay** [comment]
I need more information. Can't debug based on that.

**Comment by affinitycloud** [comment]
It appears to be working now anyway Jeff but if it happens again what would you need mate?

**Comment by careyestes** [comment]
Im getting this error now. Any info on what could be throwing this error?
Im running gulp 3.8.11.
