### ISSUE TITLE
TypeError: Arguments to path.join must be strings in Elixir

### ISSUE THREAD

**Issue by nkornel** [laravel/elixir#215]
After updating ```node``` to **0.12.7** and ```npm``` to ***2.11.3***, when running the ```gulp``` command in my project I keep getting the ```TypeError: Arguments to path.join must be strings``` error, when the sass task starts.

My laravel version is 5.0.

**Comment by laracasts** [comment]
- Which version of Elixir are you using?
- Paste your Gulpfile in (or the relevant portion)

**Comment by nkornel** [comment]
I assume - based on the package file - 3.0.5.

```
var elixir = require('laravel-elixir');

var bootstrapAssets = '/vendor/bower_components/bootstrap-sass-official/assets/';
var sbAdminAssets = '/vendor/bower_components/startbootstrap-sb-admin-2/dist/';

elixir(function(mix) {
  /**
   * Basic resources
   *
   */
  mix.sass()
     .coffee()

```

Other than this, I have a lot of ```.copy``` for the pre-loaded bower packages.

**Comment by nkornel** [comment]
Maybe this helps too:

```
[16:52:46] TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:488:13)
    at prefixOne (/home/vagrant/Dev/projectX/node_modules/laravel-elixir/GulpPaths.js:89:18)
    at GulpPaths.prefix (/home/vagrant/Dev/projectX/node_modules/laravel-elixir/GulpPaths.js:98:12)
    at GulpPaths.src (/home/vagrant/Dev/projectX/node_modules/laravel-elixir/GulpPaths.js:22:16)
    at prepGulpPaths (/home/vagrant/Dev/projectX/node_modules/laravel-elixir/tasks/sass.js:56:10)
    at null.definition (/home/vagrant/Dev/projectX/node_modules/laravel-elixir/tasks/sass.js:21:21)
    at Task.run (/home/vagrant/Dev/projectX/node_modules/laravel-elixir/Task.js:96:17)
    at Gulp.<anonymous> (/home/vagrant/Dev/projectX/node_modules/laravel-elixir/index.js:94:52)
    at module.exports (/home/vagrant/Dev/projectX/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/vagrant/Dev/projectX/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
```

**Comment by JeffreyWay** [comment]
Try setting the name of the file that you're compiling with Sass. `mix.sass('app.scss')`. Same with Coffee.

**Comment by nkornel** [comment]
Hi Mr. Way, that indeed did the trick. This syntax will be mandatory in future release?
