### ISSUE TITLE
elixir.config.js not defined

### ISSUE THREAD

**Issue by carloct** [laravel/elixir#263]
Hello, 

I'm trying to add the reactify transformer to browserfy:

    var elixir = require('laravel-elixir');

    elixir.config.js.browserify.transformers.push({
        name: 'reactify',
        options: {}
    });

    elixir(function(mix) {
        mix.sass('app.scss');
        mix.browserify('App.js');
    });

and I get this error:

    TypeError: Cannot read property 'browserify' of undefined
    at Object.<anonymous> (/Users/carlo/Dev/jscomix/gulpfile.js:15:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)

Can anyone see anything wrong in the code?

**Comment by JeffreyWay** [comment]
What version of Elixir do you have installed?

**Comment by carloct** [comment]
Hi,

"laravel-elixir": "^2.0.0"

**Comment by JeffreyWay** [comment]
Do ^3.0.0
