### ISSUE TITLE
Error parsing laravel-elixir

### ISSUE THREAD

**Issue by schel4ok** [laravel/elixir#266]
finally I was succesfull to install npm, bower and gulp without any WARN, but anyway during gulp I have laravel-elixir error

First of all I delete node_modules directory and nodejs package
```
root@schel4ok:~# rm -r /usr/lib/node_modules
root@schel4ok:~# apt-get autoremove nodejs
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  nodejs rlwrap
0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
After this operation, 27.0 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 38402 files and directories currently installed.)
Removing nodejs (0.12.7-1nodesource1~jessie1) ...
Removing rlwrap (0.41-1) ...
Processing triggers for man-db (2.7.0.2-5) ...
root@schel4ok:~# npm -v
-bash: npm: command not found
```

then I install nodejs
```
root@schel4ok:~# apt-get install -y nodejs build-essential
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version.
The following NEW packages will be installed:
  nodejs rlwrap
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/5488 kB of archives.
After this operation, 27.0 MB of additional disk space will be used.
Selecting previously unselected package rlwrap.
(Reading database ... 36083 files and directories currently installed.)
Preparing to unpack .../rlwrap_0.41-1_amd64.deb ...
Unpacking rlwrap (0.41-1) ...
Selecting previously unselected package nodejs.
Preparing to unpack .../nodejs_0.12.7-1nodesource1~jessie1_amd64.deb ...
Unpacking nodejs (0.12.7-1nodesource1~jessie1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up rlwrap (0.41-1) ...
update-alternatives: using /usr/bin/rlwrap to provide /usr/bin/readline-editor (readline-editor) in auto mode
Setting up nodejs (0.12.7-1nodesource1~jessie1) ...
root@schel4ok:~# 
```

then I install npm, bower and gulp globally without any WARN or ERROR
```
root@schel4ok:~# npm install npm -g
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
npm@2.14.0 /usr/lib/node_modules/npm
root@schel4ok:~# npm install bower -g
/usr/bin/bower -> /usr/lib/node_modules/bower/bin/bower
bower@1.5.2 /usr/lib/node_modules/bower
├── is-root@1.0.0
├── junk@1.0.2
├── stringify-object@1.0.1
├── user-home@1.1.1
├── chmodr@0.1.0
├── abbrev@1.0.7
├── archy@1.0.0
├── opn@1.0.2
├── bower-logger@0.2.2
├── bower-endpoint-parser@0.2.2
├── graceful-fs@3.0.8
├── lockfile@1.0.1
├── lru-cache@2.6.5
├── nopt@3.0.3
├── retry@0.6.1
├── tmp@0.0.24
├── request-progress@0.3.1 (throttleit@0.0.2)
├── q@1.4.1
├── semver@2.3.2
├── shell-quote@1.4.3 (array-reduce@0.0.0, array-map@0.0.0, array-filter@0.0.1, jsonify@0.0.0)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── fstream@1.0.7 (inherits@2.0.1)
├── which@1.1.1 (is-absolute@0.1.7)
├── promptly@0.2.0 (read@1.0.7)
├── p-throttler@0.1.1 (q@0.9.7)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@4.5.3 (inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.10)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.10)
├── rimraf@2.4.3 (glob@5.0.14)
├── tar-fs@1.8.1 (pump@1.0.0, tar-stream@1.2.1)
├── insight@0.5.3 (object-assign@2.1.1, lodash.debounce@3.1.1, async@0.9.2, os-name@1.0.3, tough-cookie@0.12.1)
├── decompress-zip@0.1.0 (mkpath@0.1.0, touch@0.0.3, readable-stream@1.1.13, binary@0.3.0)
├── update-notifier@0.3.2 (is-npm@1.0.0, string-length@1.0.1, semver-diff@2.0.0, latest-version@1.0.1)
├── request@2.53.0 (caseless@0.9.0, aws-sign2@0.5.0, stringstream@0.0.4, forever-agent@0.5.2, oauth-sign@0.6.0, tunnel-agent@0.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, node-uuid@1.4.3, qs@2.3.3, combined-stream@0.0.7, form-data@0.2.0, mime-types@2.0.14, http-signature@0.10.1, bl@0.9.4, tough-cookie@2.0.0, hawk@2.3.1)
├── github@0.2.4 (mime@1.3.4)
├── bower-registry-client@0.3.0 (graceful-fs@2.0.3, request-replay@0.2.0, rimraf@2.2.8, lru-cache@2.3.1, async@0.2.10, mkdirp@0.3.5, request@2.51.0)
├── cardinal@0.4.4 (ansicolors@0.2.1, redeyed@0.4.4)
├── mout@0.11.0
├── deep-sort-object@0.1.1 (mout@0.9.1)
├── bower-config@0.6.1 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1, mout@0.9.1)
├── configstore@0.3.2 (object-assign@2.1.1, xdg-basedir@1.0.1, uuid@2.0.1, osenv@0.1.3, js-yaml@3.4.0)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
└── inquirer@0.8.0 (figures@1.3.5, ansi-regex@1.1.1, mute-stream@0.0.4, through@2.3.8, readline2@0.1.1, chalk@0.5.1, lodash@2.4.2, cli-color@0.3.3, rx@2.5.3)
root@schel4ok:~# npm install gulp -g
/usr/bin/gulp -> /usr/lib/node_modules/gulp/bin/gulp.js
gulp@3.9.0 /usr/lib/node_modules/gulp
├── pretty-hrtime@1.0.0
├── interpret@0.6.5
├── deprecated@0.0.1
├── archy@1.0.0
├── tildify@1.1.0 (os-homedir@1.0.1)
├── minimist@1.2.0
├── v8flags@2.0.10 (user-home@1.1.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── semver@4.3.6
├── orchestrator@0.3.7 (sequencify@0.0.7, stream-consume@0.1.0, end-of-stream@0.1.5)
├── liftoff@2.1.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
├── gulp-util@3.0.6 (object-assign@3.0.0, array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, vinyl@0.5.1, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)
```

then I go to my laravel directory and according to http://laravel.com/docs/5.1/elixir#installation make *npm install* locally
```
root@schel4ok:/var/www/mysite# npm install
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN optional dep failed, continuing fsevents@0.3.8
Killed
```

next try
```
root@schel4ok:/var/www/mysite# npm install
npm WARN unmet dependency /var/www/mysite/node_modules/laravel-elixir/node_modules/browserify requires glob@'^4.0.5' but will load
npm WARN unmet dependency /var/www/mysite/node_modules/laravel-elixir/node_modules/glob,
npm WARN unmet dependency which is version 5.0.14
npm WARN unmet dependency /var/www/mysite/node_modules/laravel-elixir/node_modules/gulp-phpspec/node_modules/jshint requires lodash@'3.7.x' but will load
npm WARN unmet dependency /var/www/mysite/node_modules/laravel-elixir/node_modules/gulp-phpspec/node_modules/lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency /var/www/mysite/node_modules/laravel-elixir/node_modules/gulp-phpspec/node_modules/gulp-logger/node_modules/gulp-util requires chalk@'^1.0.0' but will load
npm WARN unmet dependency /var/www/mysite/node_modules/laravel-elixir/node_modules/gulp-phpspec/node_modules/gulp-logger/node_modules/chalk,
npm WARN unmet dependency which is version 0.5.1
npm WARN unmet dependency /var/www/mysite/node_modules/laravel-elixir/node_modules/gulp-phpspec/node_modules/gulp-logger/node_modules/gulp-util requires through2@'^2.0.0' but will load
npm WARN unmet dependency /var/www/mysite/node_modules/laravel-elixir/node_modules/gulp-phpspec/node_modules/gulp-logger/node_modules/through2,
npm WARN unmet dependency which is version 0.5.1
npm WARN unmet dependency /var/www/mysite/node_modules/laravel-elixir/node_modules/gulp-phpunit/node_modules/gulp-util/node_modules/dateformat/node_modules/meow requires minimist@'^1.1.0' but will load
npm WARN unmet dependency /var/www/mysite/node_modules/laravel-elixir/node_modules/gulp-phpunit/node_modules/gulp-util/node_modules/minimist,
npm WARN unmet dependency which is version 0.2.0
npm WARN unmet dependency /var/www/mysite/node_modules/laravel-elixir/node_modules/gulp-rev-replace/node_modules/gulp-util/node_modules/dateformat/node_modules/meow requires minimist@'^1.1.0' but will load
npm WARN unmet dependency /var/www/mysite/node_modules/laravel-elixir/node_modules/gulp-rev-replace/node_modules/gulp-util/node_modules/minimist,
npm WARN unmet dependency which is version 0.2.0
npm WARN unmet dependency /var/www/mysite/node_modules/laravel-elixir/node_modules/watchify/node_modules/browserify requires glob@'^4.0.5' but will load
npm WARN unmet dependency /var/www/mysite/node_modules/laravel-elixir/node_modules/glob,
npm WARN unmet dependency which is version 5.0.14
npm WARN unmet dependency /var/www/mysite/node_modules/laravel-elixir/node_modules/watchify/node_modules/browserify requires through2@'^1.0.0' but will load
npm WARN unmet dependency /var/www/mysite/node_modules/laravel-elixir/node_modules/watchify/node_modules/through2,
npm WARN unmet dependency which is version 0.6.5
```

then I try to compile my gulpfile.js and get error
```
root@schel4ok:/var/www/mysite# gulp
module.js:338
    throw err;
          ^
Error: Cannot find module 'core-util-is'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/mysite/node_modules/gulp/node_modules/gulp-util/node_modules/through2/node_modules/readable-stream/lib/_stream_duplex.js:26:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

so it seems that problem in elixir

**Comment by schel4ok** [comment]
I tried this on Debian 7, Debian 8 and Ubuntu 14.04
Every time I install laravel-elixir I have the same WARN 

npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN optional dep failed, continuing fsevents@0.3.8

and I think that is why cannot compile my gulpfile.js.

**Comment by JeffreyWay** [comment]
Looks like things aren't being installed properly on your machine. Not sure that this is an Elixir issue.

**Comment by arcanedev-maroc** [comment]
Same thing as @schel4ok on Windows 8 and I can't compile my gulpfile.js.

**Comment by bl4ckdu5t** [comment]
Any solutions to this yet? I'm running it in homestead and still get this. It's requesting that some glob be installed and I tried to install npm glob but still not working

**Comment by arcanedev-maroc** [comment]
@bl4ckdu5t I've switched to plain gulp.

**Comment by OzanKurt** [comment]
Seems like there are many people who has this issue, will you try to provide a solution? Because it completely removes the gulp part of Laravel, which is kind of painful for back-end developers.

**Comment by JeffreyWay** [comment]
Seems this happens when you prematurely abort npm install.

PolymerElements/polymer-starter-kit#51

**Comment by schel4ok** [comment]
This problem is the result of errors during npm install.
I noticed that I always have problems when I try to npm install g

~~~
npm install npm -g
npm install bower -g
npm install gulp -g
npm install rimraf -g
~~~

So I deleted npm completely, then install npm locally in project directory and it works.

**Comment by bl4ckdu5t** [comment]
How could you have installed npm with npm? js. Btw the -g for gulp helps you install the cli just like grunt-cli needs -g so we don't do global for regular packages

**Comment by hhsadiq** [comment]
I am also having same issue. Working on mac and homestead. What was the final solution which worked..? I have deleted node_modules directory and reinstalled npm but still no luck

**Comment by hhsadiq** [comment]
I was able to solve this issue by not running commands from vagrant homestead. Instead I installed node and npm on local mac and then installed gulp using npm, and everything worked fine.

There is some issue with running these commands on vagrant homestead

**Comment by bl4ckdu5t** [comment]
I just switched from Lumen that was failing for me in so many other ways to Laravel and it was all good.

**Comment by intrepido** [comment]
I have the same issue too in vagrant, I get this error every time "UNMET DEPENDENCY laravel-elixir@^4.0.0". Any solution? for now I'm running "npm install" locally on Windows.
