### ISSUE TITLE
Elixir Gulp Production Throws an Error

### ISSUE THREAD

**Issue by superKalo** [laravel/elixir#289]
Hi all,

I am having a strange error. My gulpfile.js is simply:
```javascript 
var elixir = require('laravel-elixir');
var gulp = require('gulp');

elixir(function(mix) {
    mix.sass('style.scss', 'public/css/style.css');
});
```

I run `gulp` in the console, no problem. All good. But then I try to run `gulp --production` the following error in thrown:
```
[16:16:43] Using gulpfile ~/Sites/one-studio/gulpfile.js
[16:16:43] Starting 'default'...
[16:16:43] Starting 'sass'...
[16:16:43] Running Sass: resources/assets/sass/style.scss
[16:16:43] Finished 'default' after 473 ms
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at DestroyableTransform.emit (events.js:87:13)
    at DestroyableTransform.onerror (/Users/superkalo/Sites/one-studio/node_modules/laravel-elixir/node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at DestroyableTransform.emit (events.js:107:17)
    at onwriteError (/Users/superkalo/Sites/one-studio/node_modules/laravel-elixir/node_modules/gulp-minify-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:250:10)
    at onwrite (/Users/superkalo/Sites/one-studio/node_modules/laravel-elixir/node_modules/gulp-minify-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:268:5)
    at WritableState.onwrite (/Users/superkalo/Sites/one-studio/node_modules/laravel-elixir/node_modules/gulp-minify-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:106:5)
    at afterTransform (/Users/superkalo/Sites/one-studio/node_modules/laravel-elixir/node_modules/gulp-minify-css/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:104:5)
    at TransformState.afterTransform (/Users/superkalo/Sites/one-studio/node_modules/laravel-elixir/node_modules/gulp-minify-css/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at /Users/superkalo/Sites/one-studio/node_modules/laravel-elixir/node_modules/gulp-minify-css/index.js:113:9
```

Can anyone help me?

Thanks in Advance!
Kalo.

**Comment by superKalo** [comment]
Pfu, I finally found a solution!

Issue was caused because I tried to import .css files from my main style.scss file. So what I did finally is first to compile scss to css and then - to combine all css libraries plus my compiled css like this:
```javascript
var elixir = require('laravel-elixir');
var gulp = require('gulp');

elixir(function(mix) {
    mix.sass('style.scss', 'public/css/style.css')
    .styles([
        '../lib/select2/dist/css/select2.css',

        '../lib/medium-editor/dist/css/medium-editor.min.css',
        '../lib/medium-editor/dist/css/themes/flat.css',
        '../lib/medium-editor-insert-plugin/dist/css/medium-editor-insert-plugin.min.css',

        '../../../public/css/style.css'
    ], 'public/css/style.css');
});
