### ISSUE TITLE
Gulp not working on new install of laravel

### ISSUE THREAD

**Issue by JimmyHowe** [laravel/elixir#359]
Installed a fresh Laravel project and ran npm install, then gulp and I get this error...

    module.js:340
        throw err;
        ^

    Error: Cannot find module 'vinyl'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:289:25)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous>     (C:\Users\jimmy\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-util\index.js:2:9)
        at Module._compile (module.js:425:26)
        at Object.Module._extensions..js (module.js:432:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:313:12)
        at Module.require (module.js:366:17)

**Comment by obonyojimmy** [comment]
am also facing same issue here npm fails to install laravel-elixir 

 npm install laravel-elixir
npm WARN install Couldn't install optional dependency: Unsupported
extract -> gunzTarPerm    | |###################################################################################-----------------------------------|
Killed

**Comment by JeffreyWay** [comment]
Can you guys confirm that you're using the latest versions of Node and NPM?

**Comment by obonyojimmy** [comment]
am using 
node v5.0.0
 npm  v3.3.6

**Comment by JimmyHowe** [comment]
Yep, pretty much reinstalled everything and its working fine now
