### ISSUE TITLE
Error using elixir version

### ISSUE THREAD

**Issue by mcervino** [laravel/elixir#404]
Hi All,

I get the following error using elixir.version(): 

/node_modules/laravel-elixir/tasks/version.js:73
        .output(buildPath || config.get('public.versioning.buildFolder'));
                                    ^

TypeError: config.get is not a function
    at prepGulpPaths (/home/vagrant/Code/figata-base/node_modules/laravel-elixir/tasks/version.js:73:37)
    at Function.<anonymous> (/home/vagrant/Code/figata-base/node_modules/laravel-elixir/tasks/version.js:24:17)
    at Function.<anonymous> (/home/vagrant/Code/figata-base/node_modules/laravel-elixir/index.js:40:18)
    at /home/vagrant/Code/figata-base/gulpfile.js:29:8
    at Elixir (/home/vagrant/Code/figata-base/node_modules/laravel-elixir/index.js:16:5)
    at Object.<anonymous> (/home/vagrant/Code/figata-base/gulpfile.js:20:1)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

This is my Gulpfile.js => 

elixir(function(mix) {
    mix.task('css', './resources/assets/sass/**/*.scss')
      .task('javascript-handling', './resources/assets/js/*.js')
      .task('javascript-copy', './resources/assets/js/vendor/*')
      .task('img-compressor', './resources/images/*')
      .task('copy-files', './resources/files/*')
      .browserSync({
        proxy: 'laravel.dev'
      }) 
      .version('/public/css/bundle.css');
});

Version has always worked untill a few hours ago, but i don't know what i have changed that produced this error. 

Hope someone has the right answer!

**Comment by JeffreyWay** [comment]
Can you verify which version of Elixir you have installed?

**Comment by mcervino** [comment]
Hi JeffreyWay,

Thanks for replying. 

This is the version that i use: 
"laravel-elixir": "^4.2.0"
