### ISSUE TITLE
An error occured in task 'sass'.

### ISSUE THREAD

**Issue by trevorwestca** [laravel/elixir#442]
Error: /media/dev/www/bc_build/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-11/binding.node: failed to map segment from shared object: Operation not permitted
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/media/dev/www/bc_build/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:16:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
[16:31:15] Error in plugin 'run-sequence'
Message:
    An error occured in task 'sass'.

mix.sass(['app.scss']); is all i have in my gulpfile.js

Running node v0.10.25
npm 1.3.10
Laravel 5.2

This is basically a fresh install of Laravel.

Any ideas?

**Comment by JeffreyWay** [comment]
No idea, can't reproduce. Try deleting your "node_modules" directory and reinstalling.

**Comment by joenmarz** [comment]
@JeffreyWay there are 2 "node_modules" found in my Linux distro. One is in my current Laravel project directrory, another is in /usr/local/lib directory

Question: should I delete it both?
