### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by WebtoolsWendland** [laravel/elixir#448]
Hello, 

I get the following error using gulp watch:

TypeError: Cannot read property 'indexOf' of undefined
    at /.../node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:25:16
    at Array.reduce (native)
    at processPatterns (/.../node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:24:30)
    at Object.globule.find (/.../node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:76:17)
    at Gaze.add (/.../node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:174:19)
    at new Gaze (/.../node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:74:10)
    at gaze (/.../node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:86:10)
    at Object.module.exports [as watch] (/.../node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:12:17)
    at Gulp.watch (/.../node_modules/gulp/index.js:40:14)
    at /.../node_modules/laravel-elixir/tasks/watch.js:40:18

Laravel Framework version 5.2.21

**Comment by JeffreyWay** [comment]
I need more information.

Paste in your gulpfile.

**Comment by WebtoolsWendland** [comment]
https://gist.github.com/WebtoolsWendland/b8470a83202c526fc259#file-gulpfile
