### ISSUE TITLE
Can not read property of Undefined

### ISSUE THREAD

**Issue by kadnan** [laravel/elixir#466]
Following is error dump:

```

[16:49:14] 'sass' errored after 322 ms
[16:49:14] TypeError: Cannot read property 'init' of undefined
    at module.exports (/Clients/St/wadd/sourcecode/node_modules/laravel-elixir/tasks/shared/Css.js:16:51)
    at null.definition (/Clients/St/wadd/sourcecode/node_modules/laravel-elixir/tasks/sass.js:23:16)
    at Task.run (/Clients/St/wadd/sourcecode/node_modules/laravel-elixir/Task.js:96:17)
    at Gulp.<anonymous> (/Clients/St/wadd/sourcecode/node_modules/laravel-elixir/index.js:94:52)
    at module.exports (/Clients/St/wadd/sourcecode/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Clients/St/wadd/sourcecode/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Clients/St/wadd/sourcecode/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Clients/St/wadd/sourcecode/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Clients/St/wadd/sourcecode/node_modules/run-sequence/index.js:88:16)
    at runSequence (/Clients/St/wadd/sourcecode/node_modules/run-sequence/index.js:99:2)
[16:49:14] Error in plugin 'run-sequence'
Message:
    An error occured in task 'sass'.
[16:49:14] Finished 'default' after 368 ms
```

**gulpfile.js**
```
//var elixir = require('laravel-elixir');
//
///*
// |--------------------------------------------------------------------------
// | Elixir Asset Management
// |--------------------------------------------------------------------------
// |
// | Elixir provides a clean, fluent API for defining some basic Gulp tasks
// | for your Laravel application. By default, we are compiling the Sass
// | file for our application, as well as publishing vendor resources.
// |
// */
//
//elixir(function(mix) {
//    mix.sass('app.scss');
//});


var elixir = require('laravel-elixir');
require('laravel-elixir-livereload');
require('laravel-elixir-eslint');

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Sass
 | file for our application, as well as publishing vendor resources.
 |
 */

elixir(function(mix) {
    mix
        .sass('app.scss')
        .eslint('resources/assets/js/**/*.js')
        .browserify('app.js')
        .livereload()
});

```

**Comment by JeffreyWay** [comment]
Can you try removing the Elixir plugins and try again with just laravel-elixir?

**Comment by kadnan** [comment]
I could not produce it. What I did that copied and pasted Elixir files from previous Laravel project and it worked as I was not able to figure out reason of this error. Most probably plugin was missing.
