### ISSUE TITLE
An error occured in task 'sass'.

### ISSUE THREAD

**Issue by joenmarz** [laravel/elixir#469]
Continuing the issue https://github.com/laravel/elixir/issues/442

I was following the article http://learninglaravel.net/quick-start-guide-laravel-5-bootstrap-3-vuejs
then got stuck on step 3.

inside my project already deleted the "node_modules", then try to reinstall

> sudo npm install

the last result was:

> ...
├─┬ vue@1.0.20 
│ └─┬ envify@3.4.0 
│   └─┬ jstransform@10.1.0 
│     ├── base62@0.1.1 
│     ├── esprima-fb@13001.1001.0-dev-harmony-fb 
│     └── source-map@0.1.31 
└── vue-resource@0.7.0 
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.9

Then I tried to

> sudo gulp

The result was:

> [16:08:15] Using gulpfile /media/joenmarz/DATA/PHP/codes/project1/gulpfile.js
[16:08:15] Starting 'default'...
[16:08:15] Starting 'sass'...
[16:08:15] 'sass' errored after 43 ms
[16:08:15] Error: /media/joenmarz/DATA/PHP/codes/project1/node_modules/node-sass/vendor/linux-x64-11/binding.node: failed to map segment from shared object: Operation not permitted
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/media/joenmarz/DATA/PHP/codes/project1/node_modules/node-sass/lib/index.js:16:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
[16:08:15] Error in plugin 'run-sequence'
Message:
    An error occured in task 'sass'.
[16:08:15] Finished 'default' after 58 ms

**Comment by JeffreyWay** [comment]
Since we already have an issue for this, closing.
