### ISSUE TITLE
throw er; // Unhandled 'error' event on gulp --production

### ISSUE THREAD

**Issue by mprandot** [laravel/elixir#493]
Hello!
I get error when run `gulp --production` , but, when i run only `gulp` the error not occurs
Someone can help me?

Error : 
```
events.js:154
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/var/www/html/siscomv2/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (/var/www/html/siscomv2/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1534:11)
    at croak (eval at <anonymous> (/var/www/html/siscomv2/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2026:9)
    at token_error (eval at <anonymous> (/var/www/html/siscomv2/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2034:9)
    at expect_token (eval at <anonymous> (/var/www/html/siscomv2/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2047:9)
    at expect (eval at <anonymous> (/var/www/html/siscomv2/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2050:36)
    at eval (eval at <anonymous> (/var/www/html/siscomv2/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2610:13)
    at eval (eval at <anonymous> (/var/www/html/siscomv2/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2073:24)
    at expr_atom (eval at <anonymous> (/var/www/html/siscomv2/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2540:35)
    at maybe_unary (eval at <anonymous> (/var/www/html/siscomv2/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2716:19)
```
My gulpfile.js
```
var elixir = require('laravel-elixir');
elixir(function (mix) {

    mix.browserify('Vue/main.js');
    mix.styles([
        'bootstrap.min.css',
        'plugins.css',
        'main.css',
        'themes/passion.css',
        'themes.css',
        'rbr/customrbr.css',
        'rbr/details.css',
        'rbr/forms.css'
    ], 'public/css/layout-one.css');

    mix.scripts([
        'vendor/modernizr-2.8.3.min.js',
        'vendor/jquery-2.2.0.min.js',
        'vendor/bootstrap.min.js',
        '../../../node_modules/lodash/lodash.js',
        '../../../node_modules/moment/moment.js',
        '../../../node_modules/moment/locale/pt-br.js',
        'plugins.js',
        'app.js',
        'pages/uiTables.js',
        'rbr/Company.js',
        'rbr/HelpFunctions.js',
        'rbr/BillsForm.js',
        'rbr/MaskFields.js',
        'rbr/MakeSelect2Plugin.js',
        'rbr/InputValidation.js',
        'rbr/Pessoas/PessoasDep.js',
        'rbr/Pessoas/PessoasUtils.js',
        'rbr/Produtos/ProdutosDep.js',
        'rbr/Prospeccoes/ProspeccaoDep.js',
        'rbr/OrdemServico/Index.js',
        'rbr/OrdemServico/FormOs.js'
    ], 'public/js/layout-one.js');

    mix.copy('resources/assets/css/fonts', 'public/build/css/fonts');
    mix.copy('resources/assets/css/themes', 'public/build/css/themes');
    mix.copy('resources/assets/fonts', 'public/build/fonts');
    mix.copy('resources/assets/img', 'public/build/img');
    mix.copy('resources/assets/images', 'public/images');
    mix.copy('resources/assets/js/pages', 'public/build/js/pages');
    mix.copy('resources/assets/js/plugins', 'public/build/js/plugins');
    mix.copy('resources/assets/js/vendor', 'public/build/js/vendor');

    mix.scripts([
        'rbr/Graphics/prospectionGraphics.js'
    ], 'public/js/graphics.js');

    mix.version([
        'css/layout-one.css',
        'js/layout-one.js',
        'js/graphics.js']);
});
```

**Comment by vinkla** [comment]
Seems to be an issue with `uglify`. Try removing one JS file at the time from `mix.scripts` and try running `gulp --production` again. Do that until it works. Then you know which file that could be broken.

**Comment by JeffreyWay** [comment]
Yeah, it has to be related to Uglify. As @vinkla said, try one file at a time and let us know what you find.

**Comment by mprandot** [comment]
Ok!
This error happened from nothing, 
I did not change any js, but, i will test...

**Comment by mprandot** [comment]
Bug found!
Sintax error in one .js!

Thanks :heart: !

**Comment by vinkla** [comment]
👍

**Comment by HenoTaMyJIb** [comment]
Same error.
I'm using browserify and Vue. One of components (not written by me, npm installed) uses ES6 arrow function syntax and uglify-js does not support es6.

I'm not sure what should I do to run `gulp --production` without errors?

**Comment by mprandot** [comment]
@HenoTaMyJIb  

I think this error is sintax error.
Past your javascript here : http://www.javascriptlint.com/online_lint.php
If has sintax error this will show.

**Comment by krisanalfa** [comment]
Same issue here. Strange, it works without `--production` flag.

**Comment by mprandot** [comment]
@krisanalfa  is a JS sintax error! 

Put your "last" js here: http://www.javascriptlint.com/online_lint.php and look for errors

**Comment by krisanalfa** [comment]
Hi @mprandot, thank for your response. I believe it's not syntax error. This issue only occurred when I use `webpack`. After I switched to `browserify` the error gone. What's the problem?

**Comment by christophwolff** [comment]
+1

**Comment by HenoTaMyJIb** [comment]
Yea, for me the syntax error was caused by ES6 syntax (arrow functions). Pre-compiling with babel helped.
