### ISSUE TITLE
gulp  watch does not work

### ISSUE THREAD

**Issue by caijinlin** [laravel/elixir#507]
I have got the next errors when I run gulp watch, please help me.

 gulp[8236] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:896:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1400:11

**Comment by JeffreyWay** [comment]
More information about your OS please.

**Comment by Yilene** [comment]
@JeffreyWay Hi，I have got the same error:
[15:43:31] Starting 'sass:watch'...
2016-06-24 15:43 gulp[37954] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
[15:43:31] Finished 'sass:watch' after 8.85 ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:953:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1400:11)


My OS information: OS X Yosemite   10.10.2

**Comment by caijinlin** [comment]
@JeffreyWay @Yilene when the opened files is too much , it will occur.  eg sublime
