### ISSUE TITLE
Cannot find module 'laravel-elixir/Notification'

### ISSUE THREAD

**Issue by Grawl** [laravel/elixir#528]
Just updated Elixir to `6.0.0-2` and cannot launch it now:

```
module.js:442
    throw err;
    ^

Error: Cannot find module 'laravel-elixir/Notification'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/grawl/Sites/zawjeen/node_modules/laravel-elixir-postcss/index.js:5:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

Downgrade back to `^4.0.0` (`4.2.1`) works normally.

**Comment by JeffreyWay** [comment]
Looks like this is related to the laravel-elixir-postcss plugin you're pulling in.

v6 isn't officially out yet, so closing this for now.

**Comment by Grawl** [comment]
👌
