### ISSUE TITLE
laravel elixir 6.0 with stylus

### ISSUE THREAD

**Issue by eternia89** [laravel/elixir#537]
getting error when using **gulp** command.
any idea ?
Thanks..

node -v
**v6.2.1**

npm -v
**3.9.3**

**here's the report**

(node:78957) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
module.js:442
    throw err;
    ^

Error: Cannot find module 'laravel-elixir/dist/tasks/CssTask'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/eternia89/code/jakmall/node_modules/laravel-elixir-stylus/index.js:1:77)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by thasmog** [comment]
+1

**Comment by xmoki** [comment]
+1

**Comment by JeffreyWay** [comment]
Upgrade to the latest Elixir 6 pre-release.
