### ISSUE TITLE
gulp-sass error: TypeError: Cannot assign to read only property 'data' of ./

### ISSUE THREAD

**Issue by stueynet** [laravel/elixir#542]
Since npm update last week, gulp-sass is failing. Any help would be appreciated.
```
Saving To...
   - public/css/app.css

/Users/stueynet/Sites/maple-app/node_modules/gulp-sass/index.js:38
    opts.data = file.contents.toString();
              ^

TypeError: Cannot assign to read only property 'data' of ./
    at DestroyableTransform._transform (/Users/stueynet/Sites/maple-app/node_modules/gulp-sass/index.js:38:15)
    at DestroyableTransform.Transform._read (/Users/stueynet/Sites/maple-app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/stueynet/Sites/maple-app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/stueynet/Sites/maple-app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Users/stueynet/Sites/maple-app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/Users/stueynet/Sites/maple-app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at DestroyableTransform.ondata (/Users/stueynet/Sites/maple-app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:531:20)
    at emitOne (events.js:77:13)
    at DestroyableTransform.emit (events.js:169:7)
    at readableAddChunk (/Users/stueynet/Sites/maple-app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:198:18)

```

**Comment by stueynet** [comment]
If anyone else is having this issue it is solved by forcing gulp-sass back to 2.3.1 in your package.json

        "gulp-sass": "2.3.1",

**Comment by StefanoMagrassi** [comment]
@JeffreyWay I checked out the package.json and the `gulp-sass` dependency is already updated to `^2.3.1` version: I think this issue can be closed

**Comment by stueynet** [comment]
Thats not the issue. The problem is that 2.3.2 breaks. The package.json file for Elixir has 

      "gulp-sass": "^2.3.1",

That will install 2.3.2.

**Comment by dschu-lab** [comment]
Hey? This issue is still present
```
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.9.1"
  },
  "dependencies": {
    "laravel-elixir": "^4.2.1"
  }
}
```

results in 

```
/home/julian/Dokumente/frontend/node_modules/gulp-sass/index.js:38
    opts.data = file.contents.toString();
              ^

TypeError: Cannot assign to read only property 'data' of resources/assets/css/
[...]
```

**Comment by JeffreyWay** [comment]
Never seen that before, but update to Laravel Elixir 5. That's an old version.

**Comment by dschu-lab** [comment]
Tried that, no progress :sweat_smile:

**Comment by JeffreyWay** [comment]
What does your Gulpfile look like? And what is the code here...

```
Cannot assign to read only property 'data' of resources/assets/css/
[...]
```

**Comment by dschu-lab** [comment]
gulpfile.js
```
process.env.DISABLE_NOTIFIER = true;

var elixir = require('laravel-elixir');

// disable source maps
elixir.config.sourcemaps = false;

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Sass
 | file for our application, as well as publishing vendor resources.
 |
 */

elixir( function( mix )
{
    mix.sass( [ 'style.scss' ], 'public/css/style.css', 'resources/assets/css/' );

    mix.scripts( [ 'vendor/jquery-2.2.4.js', 'vendor/jquery.cookie.js' ], 'public/js/vendor.js' )
       .scripts( [ 'global.js' ], 'public/js/global.js' );

    mix.scripts( [ 'vendor/jquery-2.2.4.js', 'vendor/html5sortable/html.sortable.js', 'admin.js'  ], 'public/js/admin.js' );
    mix.scripts( [ 'vendor/jquery-2.2.4.js', 'vendor/isotope/dist/isotope.pkgd.min.js', 'vendor/imagesloaded/imagesloaded.pkgd.js', 'blog.js'  ], 'public/js/blog.js' );
    mix.scripts( [ 'ckeditor/config.js' ], 'public/js/ckeditor/config.js' );

    mix.version( [ 'css/style.css', 'js/vendor.js', 'js/global.js', 'js/admin.js', 'js/blog.js', 'public/js/ckeditor/config.js' ] );
});
```

Stacktrace
```
[16:52:35] Using gulpfile ~/Dokumente/frontend/gulpfile.js
[16:52:35] Starting 'default'...
[16:52:35] Starting 'sass'...

Fetching Sass Source Files...
   - resources/assets/sass/style.scss


Saving To...
   - public/css/style.css

[16:52:35] Finished 'default' after 528 ms
/home/julian/Dokumente/frontend/node_modules/laravel-elixir/node_modules/gulp-sass/index.js:38
    opts.data = file.contents.toString();
              ^

TypeError: Cannot assign to read only property 'data' of resources/assets/css/
    at DestroyableTransform._transform (/home/julian/Dokumente/frontend/node_modules/laravel-elixir/node_modules/gulp-sass/index.js:38:15)
    at DestroyableTransform.Transform._read (/home/julian/Dokumente/frontend/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/julian/Dokumente/frontend/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/home/julian/Dokumente/frontend/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/home/julian/Dokumente/frontend/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/home/julian/Dokumente/frontend/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at write (/home/julian/Dokumente/frontend/node_modules/laravel-elixir/node_modules/gulp-if/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/julian/Dokumente/frontend/node_modules/laravel-elixir/node_modules/gulp-if/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/home/julian/Dokumente/frontend/node_modules/laravel-elixir/node_modules/gulp-if/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
```

**Comment by dschu-lab** [comment]
I figured out what was causing the error: It was the thrid parameter of mix.sass withing the gulpfile.
After changing `mix.sass( [ 'style.scss' ], 'public/css/style.css', 'resources/assets/css/' );` to `mix.sass( [ 'style.scss' ], 'public/css/style.css' );` everything went back to normal.

**Comment by brandonferens** [comment]
I agree with @dschu-lab. I had a third param in there for when I was using ruby-sass to compile the css. Removed that and it works just fine now.
