### ISSUE TITLE
Error running task

### ISSUE THREAD

**Issue by xcopy** [laravel/elixir#568]
Hey there.

Getting this errors when run the `gulp` command in terminal.

```
[15:14:36] Using gulpfile /path/to/project/gulpfile.js
[15:14:36] Starting 'default'...
[15:14:36] Starting 'angular:cache:templates'...
[15:14:36] Finished 'default' after 28 ms
[15:14:37] Finished 'angular:cache:templates' after 146 ms
[15:14:37] Starting 'task'...
[15:14:37] Starting 'angular:cache:templates'...
[15:14:37] 'angular:cache:templates' errored after 81 μs
[15:14:37] TypeError: Cannot read property 'run' of undefined
    at Gulp.<anonymous> (/path/to/project/node_modules/laravel-elixir/index.js:89:51)
    at module.exports (/path/to/project/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/path/to/project/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/path/to/project/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/path/to/project/node_modules/orchestrator/index.js:134:8)
    at .definition (/path/to/project/node_modules/laravel-elixir/tasks/task.js:17:21)
    at Task.run (/path/to/project/node_modules/laravel-elixir/Task.js:94:17)
    at Gulp.<anonymous> (/path/to/project/node_modules/laravel-elixir/index.js:89:52)
    at module.exports (/path/to/project/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/path/to/project/node_modules/orchestrator/index.js:273:3)
[15:14:37] Error in plugin 'run-sequence(angular:cache:templates)'
Message:
    angular:cache:templates catch
[15:14:37] Finished 'task' after 7.56 ms
```

Gulpfile.js

```js
var gulp = require('gulp');
var elixir = require('laravel-elixir');
var templateCache = require('gulp-angular-templatecache');
var Task = elixir.Task;

new Task('angular:cache:templates', function () {
    var paths = [
        'resources/assets/views/*.html',
        'resources/assets/js/directives/*.html'
    ];

    return gulp.src(paths)
        .pipe(templateCache())
        .pipe(gulp.dest('resources/assets/js/templates'));
})
    .watch('resources/assets/views/*.html')
    .watch('resources/assets/js/directives/*.html');

elixir.config.sourcemaps = false;

elixir(function(mix) {
   // ...
    mix.task('angular:cache:templates');
   // ...
});
```

package.json

```json
{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-angular-templatecache": "^2.0.0",
    "laravel-elixir": "^5.0.0"
  }
}
```

**Comment by JeffreyWay** [comment]
If you're using mix.task(), then your actual task should take the form of `gulp.task()`. See the docs here:

https://laravel.com/docs/5.2/elixir#calling-existing-gulp-tasks

**Comment by xcopy** [comment]
@JeffreyWay, thanks.
