### ISSUE TITLE
Elixir v6.0.0-8 & laravel-elixir-vue error

### ISSUE THREAD

**Issue by Eldair** [laravel/elixir#573]
There is an issue when using Elixir v6.0.0-8 with laravel-elixir-vue and running gulp command:
```
TypeError: Cannot read property 'loaders' of undefined
    at Object.<anonymous> (C:\Code\test\node_modules\laravel-elixir-vue\main.js:3:25)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Code\test\gulpfile.js:3:1)
    at Module._compile (module.js:541:32)
```
It seems that Elixir is not bootstraped before elixir-vue is required.
Of course, laravel-elixir-webpack-official is also installed.

**Comment by Kauhat** [comment]
It looks like the configuration object was removed from the main project and hasn't been added to the webpack plugin yet.

In the meanwhile, it's possible to add a `webpack.config.js` file alongside the gulpfile and specify the vue loaders there, e.g.

```javascript
module.exports = {
  module: {
    loaders: [
      {
        test: /\.vue$/,
        loader: 'vue'
      }
    ],
  }
};
```
<hr>
[Relevent section of webpack plugin](https://github.com/JeffreyWay/laravel-elixir-webpack-official/blob/master/src/WebpackTask.js#L64)

**Comment by JeffreyWay** [comment]
This is fixed now. Thanks for the bug report.
