### ISSUE TITLE
Unhandled error after update

### ISSUE THREAD

**Issue by zachleigh** [laravel/elixir#575]
Just updated to laravel-elixir@4.2.1 and am getting the following error when running gulp with the --production flag.
```
events.js:154
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/home/zachleigh/Web/Elephany/node_modules/laravel-elixir/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (/home/zachleigh/Web/Elephany/node_modules/laravel-elixir/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1534:11)
    at croak (eval at <anonymous> (/home/zachleigh/Web/Elephany/node_modules/laravel-elixir/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2025:9)
    at token_error (eval at <anonymous> (/home/zachleigh/Web/Elephany/node_modules/laravel-elixir/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2033:9)
    at expect_token (eval at <anonymous> (/home/zachleigh/Web/Elephany/node_modules/laravel-elixir/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2046:9)
    at expect (eval at <anonymous> (/home/zachleigh/Web/Elephany/node_modules/laravel-elixir/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2049:36)
    at eval (eval at <anonymous> (/home/zachleigh/Web/Elephany/node_modules/laravel-elixir/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2602:13)
    at eval (eval at <anonymous> (/home/zachleigh/Web/Elephany/node_modules/laravel-elixir/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2072:24)
    at expr_atom (eval at <anonymous> (/home/zachleigh/Web/Elephany/node_modules/laravel-elixir/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2532:35)
    at maybe_unary (eval at <anonymous> (/home/zachleigh/Web/Elephany/node_modules/laravel-elixir/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2708:19)
```
The gulpfile:
```
var elixir = require('laravel-elixir');

require ('laravel-elixir-vueify');

elixir(function(mix) {
    mix.copy('node_modules/normalize.css/normalize.css', 'public/css/vendor/normalize.css')
        .sass('app.scss')
        .browserify('app.js', null, null, {
            paths: ['./node_modules', './resources/assets/js'],
            cache: {},
            packageCache: {}
        })
        .styles([
            'vendor/normalize.css',
            'app.css'
        ], 'public/css/final.css', 'public/css')
        .version('css/final.css');
});
```

**Comment by JeffreyWay** [comment]
Not immediately sure... but Elixir 6 is almost out. At the very least upgrade to v5.

**Comment by JeffreyWay** [comment]
See if you can pinpoint which part is triggering that error. I'm assuming it's when you run mix.browserify().

Also, what OS are you using?

**Comment by zachleigh** [comment]
Yes, its browserify() that triggers it.    
    
OS: Ubuntu 16.04

**Comment by zachleigh** [comment]
Had some time to look deeper into this. Running uglifyjs from the command line on the file compiled without the --production gives a little more info:
```
Parse error at public/js/app.js:1262,7
SyntaxError: Unexpected token punc «(», expected punc «:»
Error
    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)
    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)
    at croak (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at expect_token (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2110:9)
    at expect (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2113:36)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2686:13)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at expr_atom (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2616:35)
    at maybe_unary (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
```
And line 1262 in app.js:
```javascript
  data () {         // <- ln 1262
    return {
      search: '',
      isOpen: false,
      value: [],
      loading: false
    }
  },
```
This is from a Vue component I built that extends [monterail/vue-multiselect](https://github.com/monterail/vue-multiselect). This is the chain:
lang-select tags used in DOM. LangSelect.vue:
```javascript
...
    var IconSelect = require('./IconSelect.vue');

    export default {
        components: { IconSelect },
...
```
IconSelect.vue:
```javascript
...
  import multiselectMixin from './../../../../node_modules/vue-multiselect/src/multiselectMixin.js';
  import pointerMixin from './../../../../node_modules/vue-multiselect/src/pointerMixin';

  export default {
    mixins: [multiselectMixin, pointerMixin],
...
```
The offending piece of code is in multiselectMixin. Whats weird is that when using the package without extending it, it uses the same mixin and compiles fine. My extension doesnt seem to work though. Hmm.... Ill see if the package creators have any advice for me.

**Comment by aligajani** [comment]
Same here, any idea guys?
