### ISSUE TITLE
TypeError: Cannot read property 'transformers' of undefined

### ISSUE THREAD

**Issue by nacr-dev** [laravel/elixir#591]
Hello, after updating elixir to 6.0.0-9, I get this error on laravel-elixir-vueify.

If I user 6.0.0-2 all works fine, should we consider this a laravel-elixir issue or a laravel-elixir-vueify?

How can I resolve this if I'm the one doing something wrong?

```
nacr@Maze-PC ~/Code/zitauto $ gulp
/home/nacr/Code/zitauto/node_modules/laravel-elixir-vueify/index.js:3
Elixir.config.js.browserify.transformers.push({
                           ^

TypeError: Cannot read property 'transformers' of undefined
    at Object.<anonymous> (/home/nacr/Code/zitauto/node_modules/laravel-elixir-vueify/index.js:3:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nacr/Code/zitauto/gulpfile.js:3:1)
    at Module._compile (module.js:541:32)
```

**Comment by ricardogobbosouza** [comment]
In the latest version of laravel-elixir you need to install the following dependencies:
```
npm install laravel-elixir --save-dev
**npm install laravel-elixir-browserify-official --save-dev**
npm install laravel-elixir-vueify --save-dev
```
gulpfile.js

```
var elixir = require('laravel-elixir');

require('laravel-elixir-browserify-official');
require('laravel-elixir-vueify');

elixir(function(mix) {
    mix.browserify('main.js');
});
```

**Comment by nacr-dev** [comment]
@ricardogobbosouza checking that now but I believe I have already done it.

**Comment by nacr-dev** [comment]
Well, I it resolved the issue. Tks @ricardogobbosouza but I'm most certain I had done that before.

**Comment by peshkov3** [comment]
@nacr-dev How did you resolve the issue?

**Comment by DrudgeRajen** [comment]
Thank you for the info .
