### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Robot5** [laravel/elixir#601]
Default installation laravel 5.3 dev-develop.
Nodejs 6.3.1
run gulp error:

`[12:15:40] Using gulpfile E:\Web\new\gulpfile.js
[12:15:40] Starting 'all'...
[12:15:40] Starting 'sass'...
[12:15:40] 'sass' errored after 97 ms
[12:15:40] Error: ENOENT: no such file or directory, scandir 'E:\Web\new\node_modules\node-sass\vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (E:\Web\new\node_modules\node-sass\lib\extensions.js:119:13)
    at foundBinariesList (E:\Web\new\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (E:\Web\new\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (E:\Web\new\node_modules\node-sass\lib\errors.js:45:5)
    at Object.<anonymous> (E:\Web\new\node_modules\node-sass\lib\index.js:15:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)`

Don't know how to solve? thk!!!

**Comment by kroky** [comment]
Try `npm rebuild node-sass` - for some reason, the binary binding for node-sass was not installed during npm install.
