### ISSUE TITLE
Error with babel-loader after default Laravel 5.3 installation

### ISSUE THREAD

**Issue by rkgrep** [laravel/elixir#602]
Issues are closed on laravel/laravel repository, so I have to ask here.
I receive this error on node 6.x
```
$ ./node_modules/gulp/bin/gulp.js 
(node:7111) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[17:43:00] Using gulpfile ~/Code/php/swiftlet/gulpfile.js
[17:43:00] Starting 'all'...
[17:43:00] Starting 'sass'...
[17:43:01] Finished 'sass' after 827 ms
[17:43:01] Starting 'webpack'...
{ [Error: ./~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/Example.vue
Module build failed: Error: Cannot remove "babel-plugin-transform-es2015-modules-commonjs" from the plugin list.
    at Object.<anonymous> (/Users/roman.kinyakin/Code/php/swiftlet/node_modules/babel-preset-es2015-webpack/index.js:35:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /Users/roman.kinyakin/Code/php/swiftlet/node_modules/babel-core/lib/transformation/file/options/option-manager.js:324:15
    at Array.map (native)
 @ ./resources/assets/js/components/Example.vue 2:17-130
 @ ./resources/assets/js/app.js]
  message: './~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/Example.vue\nModule build failed: Error: Cannot remove "babel-plugin-transform-es2015-modules-commonjs" from the plugin list.\n    at Object.<anonymous> (/Users/roman.kinyakin/Code/php/swiftlet/node_modules/babel-preset-es2015-webpack/index.js:35:11)\n    at Module._compile (module.js:541:32)\n    at Object.Module._extensions..js (module.js:550:10)\n    at Module.load (module.js:458:32)\n    at tryModuleLoad (module.js:417:12)\n    at Function.Module._load (module.js:409:3)\n    at Module.require (module.js:468:17)\n    at require (internal/module.js:20:19)\n    at /Users/roman.kinyakin/Code/php/swiftlet/node_modules/babel-core/lib/transformation/file/options/option-manager.js:324:15\n    at Array.map (native)\n @ ./resources/assets/js/components/Example.vue 2:17-130\n @ ./resources/assets/js/app.js',
  showStack: false,
  showProperties: true,
  plugin: 'webpack-stream',
  __safety: { toString: [Function: bound ] } }
```

**Comment by PetervMeijgaard** [comment]
See https://github.com/laravel/elixir/issues/603

**Comment by rkgrep** [comment]
@PetervMeijgaard thank you!
