### ISSUE TITLE
Cannot find module while using Elixir and Webpack / Rollup

### ISSUE THREAD

**Issue by aligajani** [laravel/elixir#628]
Following @JeffreyWay 's tutorial [here](https://laracasts.com/series/es6-cliffsnotes/episodes/12), by running `.webpack('es6-sample/main-class.js')` with two sample classes placed in `resources/assets/js/es6-sample/`.

**person-class.js**

```
'use strict';

export default class Person {
    constructor(name, age, email) {
        this.name = name;
        this.age = age;
        this.email = email;
    }

    get details() {
        return `My name is ${this.name}, aged ${this.age} and contactable on the email ${this.email}`;
    }
}

```

**main-class.js**

```
'use strict';

import Person from 'es6-sample/Person'
let person = new Person('Ali Gajani', 25, 'aligajani@gmail.com');
```

Running `gulp --production` yields the following error.

```
{ [Error: ./resources/assets/js/es6-sample/main-class.js
Module not found: Error: Can't resolve 'es6-sample/Person' in '/Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/assets/js/es6-sample'
resolve 'es6-sample/Person' in '/Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/assets/js/es6-sample'
  Parsed request is a module
  using description file: /Users/aligajani/Dropbox/mrgeeklabs/saveeo/package.json (relative path: ./resources/assets/js/es6-sample)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/aligajani/Dropbox/mrgeeklabs/saveeo/package.json (relative path: ./resources/assets/js/es6-sample)
    resolve as module
      /Users/aligajani/Dropbox/mrgeeklabs/node_modules doesn't exist or is not a directory
      /Users/aligajani/Dropbox/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      /Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/assets/js/es6-sample/node_modules doesn't exist or is not a directory
      /Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/assets/js/node_modules doesn't exist or is not a directory
      /Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/assets/node_modules doesn't exist or is not a directory
      /Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/node_modules doesn't exist or is not a directory
      looking for modules in /Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules
        using description file: /Users/aligajani/Dropbox/mrgeeklabs/saveeo/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/aligajani/Dropbox/mrgeeklabs/saveeo/package.json (relative path: ./node_modules)
          using description file: /Users/aligajani/Dropbox/mrgeeklabs/saveeo/package.json (relative path: ./node_modules/es6-sample/Person)
            as directory
              /Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/es6-sample/Person doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/es6-sample/Person doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/es6-sample/Person.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/es6-sample/Person.json doesn't exist
      looking for modules in /Users/aligajani/node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
        No description file found
        as directory
          /Users/aligajani/node_modules/es6-sample/Person doesn't exist
        no extension
          Field 'browser' doesn't contain a valid alias configuration
          /Users/aligajani/node_modules/es6-sample/Person doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
          /Users/aligajani/node_modules/es6-sample/Person.js doesn't exist
        .json
          Field 'browser' doesn't contain a valid alias configuration
          /Users/aligajani/node_modules/es6-sample/Person.json doesn't exist
[/Users/aligajani/Dropbox/mrgeeklabs/node_modules]
[/Users/aligajani/Dropbox/node_modules]
[/Users/aligajani/node_modules/package.json]
[/Users/node_modules]
[/node_modules]
[/Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/assets/js/es6-sample/node_modules]
[/Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/assets/js/node_modules]
[/Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/assets/node_modules]
[/Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/node_modules]
[/Users/aligajani/node_modules/es6-sample/Person/package.json]
[/Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/es6-sample/Person]
[/Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/es6-sample/Person]
[/Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/es6-sample/Person.js]
[/Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/es6-sample/Person.json]
[/Users/aligajani/node_modules/es6-sample/Person]
[/Users/aligajani/node_modules/es6-sample/Person]
[/Users/aligajani/node_modules/es6-sample/Person.js]
[/Users/aligajani/node_modules/es6-sample/Person.json]
 @ ./resources/assets/js/es6-sample/main-class.js 3:0-38]
  message: './resources/assets/js/es6-sample/main-class.js\nModule not found: Error: Can\'t resolve \'es6-sample/Person\' in \'/Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/assets/js/es6-sample\'\nresolve \'es6-sample/Person\' in \'/Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/assets/js/es6-sample\'\n  Parsed request is a module\n  using description file: /Users/aligajani/Dropbox/mrgeeklabs/saveeo/package.json (relative path: ./resources/assets/js/es6-sample)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n  after using description file: /Users/aligajani/Dropbox/mrgeeklabs/saveeo/package.json (relative path: ./resources/assets/js/es6-sample)\n    resolve as module\n      /Users/aligajani/Dropbox/mrgeeklabs/node_modules doesn\'t exist or is not a directory\n      /Users/aligajani/Dropbox/node_modules doesn\'t exist or is not a directory\n      /Users/node_modules doesn\'t exist or is not a directory\n      /node_modules doesn\'t exist or is not a directory\n      /Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/assets/js/es6-sample/node_modules doesn\'t exist or is not a directory\n      /Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/assets/js/node_modules doesn\'t exist or is not a directory\n      /Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/assets/node_modules doesn\'t exist or is not a directory\n      /Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/node_modules doesn\'t exist or is not a directory\n      looking for modules in /Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules\n        using description file: /Users/aligajani/Dropbox/mrgeeklabs/saveeo/package.json (relative path: ./node_modules)\n          Field \'browser\' doesn\'t contain a valid alias configuration\n        after using description file: /Users/aligajani/Dropbox/mrgeeklabs/saveeo/package.json (relative path: ./node_modules)\n          using description file: /Users/aligajani/Dropbox/mrgeeklabs/saveeo/package.json (relative path: ./node_modules/es6-sample/Person)\n            as directory\n              /Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/es6-sample/Person doesn\'t exist\n            no extension\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/es6-sample/Person doesn\'t exist\n            .js\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/es6-sample/Person.js doesn\'t exist\n            .json\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/es6-sample/Person.json doesn\'t exist\n      looking for modules in /Users/aligajani/node_modules\n        No description file found\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        No description file found\n        as directory\n          /Users/aligajani/node_modules/es6-sample/Person doesn\'t exist\n        no extension\n          Field \'browser\' doesn\'t contain a valid alias configuration\n          /Users/aligajani/node_modules/es6-sample/Person doesn\'t exist\n        .js\n          Field \'browser\' doesn\'t contain a valid alias configuration\n          /Users/aligajani/node_modules/es6-sample/Person.js doesn\'t exist\n        .json\n          Field \'browser\' doesn\'t contain a valid alias configuration\n          /Users/aligajani/node_modules/es6-sample/Person.json doesn\'t exist\n[/Users/aligajani/Dropbox/mrgeeklabs/node_modules]\n[/Users/aligajani/Dropbox/node_modules]\n[/Users/aligajani/node_modules/package.json]\n[/Users/node_modules]\n[/node_modules]\n[/Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/assets/js/es6-sample/node_modules]\n[/Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/assets/js/node_modules]\n[/Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/assets/node_modules]\n[/Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/node_modules]\n[/Users/aligajani/node_modules/es6-sample/Person/package.json]\n[/Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/es6-sample/Person]\n[/Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/es6-sample/Person]\n[/Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/es6-sample/Person.js]\n[/Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/es6-sample/Person.json]\n[/Users/aligajani/node_modules/es6-sample/Person]\n[/Users/aligajani/node_modules/es6-sample/Person]\n[/Users/aligajani/node_modules/es6-sample/Person.js]\n[/Users/aligajani/node_modules/es6-sample/Person.json]\n @ ./resources/assets/js/es6-sample/main-class.js 3:0-38',
  showStack: false,
  showProperties: true,
  plugin: 'webpack-stream',
  __safety: { toString: [Function: bound ] } }

```

Tried this with `rollup()` and a similar error appears:

```
Error: Could not resolve 'es6-sample/Person' from /Users/aligajani/Dropbox/mrgeeklabs/saveeo/resources/assets/js/es6-sample/main-class.js
    at Error (native)
    at /Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:77:21
    at /Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/browser-resolve/index.js:265:24
    at /Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/resolve/lib/async.js:46:14
    at process (/Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/resolve/lib/async.js:92:31)
    at /Users/aligajani/Dropbox/mrgeeklabs/saveeo/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by laracasts** [comment]
Try:

```
import Person from 'es6-sample/person-class'
```

**Comment by gocanto** [comment]
Having the same problem after publishing my pkg to the npm store. Any luck?
