### ISSUE TITLE
gulp --production breaks for webpack with sourcemaps

### ISSUE THREAD

**Issue by terion-name** [laravel/elixir#631]
It is impossible to make minified js with sourcemaps.

Setting `elixir.config.sourcemaps = true;` results in inline maps and "minified" script with ~980kb of mess. Setting `devtool: 'inline-source-map',` for webpack alongside with `elixir.config.sourcemaps` results in absence of maps at all. Setting `devtool: 'source-map',` results in error:

```
{ Error
    at new JS_Parse_Error (eval at <anonymous> (/Volumes/HDD/my/kzmr/botan/site2016/botan2016/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/Volumes/HDD/my/kzmr/botan/site2016/botan2016/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (/Volumes/HDD/my/kzmr/botan/site2016/botan2016/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/Volumes/HDD/my/kzmr/botan/site2016/botan2016/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (/Volumes/HDD/my/kzmr/botan/site2016/botan2016/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)
    at semicolon (eval at <anonymous> (/Volumes/HDD/my/kzmr/botan/site2016/botan2016/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2123:56)
    at simple_statement (eval at <anonymous> (/Volumes/HDD/my/kzmr/botan/site2016/botan2016/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2314:73)
    at eval (eval at <anonymous> (/Volumes/HDD/my/kzmr/botan/site2016/botan2016/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2164:47)
    at eval (eval at <anonymous> (/Volumes/HDD/my/kzmr/botan/site2016/botan2016/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at block_ (eval at <anonymous> (/Volumes/HDD/my/kzmr/botan/site2016/botan2016/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2429:20)
  message: '/Volumes/HDD/my/kzmr/botan/site2016/botan2016/app.js.map: SyntaxError: Unexpected token: punc (:)',
  fileName: '/Volumes/HDD/my/kzmr/botan/site2016/botan2016/app.js.map',
  lineNumber: 1,
```

**Comment by ejdelmonico** [comment]
You are saying there is no source map at the end of your JS file (inline-source-map)? You are requesting a source map in dev environment so web pack removes it when using a production build.

**Comment by terion-name** [comment]
inline-source-map is jut for example of what is going on. I need a separate sourcemap for production script

**Comment by SebastianS90** [comment]
https://github.com/JeffreyWay/laravel-elixir-webpack-official/pull/28
