### ISSUE TITLE
Error in plugin 'run-sequence(scripts)'

### ISSUE THREAD

**Issue by sachingadagi** [laravel/elixir#632]
I am using latest version of node/npm (4.5) and laravel (5.3) as of now

I am using elixir to compile JS and CSS files into single file.
`mix.styles` and `mix.copy` work perfectly as expected
but `mix.scripts` wont run and stops with following error

 **Error in plugin 'run-sequence(scripts)'
Message:
    Cannot find module '../../modules/es6.string.iterator'
Details:
    code: MODULE_NOT_FOUND** 
`Stack:
Error: Cannot find module '../../modules/es6.string.iterator'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\installation\wamp\www\test\node_modules\laravel-el
ixir\node_modules\gulp-babel\node_modules\babel-core\node_modules\babel-runtime\
node_modules\core-js\library\fn\symbol\iterator.js:1:63)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)`

**Comment by ejdelmonico** [comment]
you need to upgrade your node installation to at least the latest 5.0 version. and it might help if you posted your gulpfile.

**Comment by saiiif** [comment]
did you find out some solution ?
