### ISSUE TITLE
Gulp --production trying to minify images

### ISSUE THREAD

**Issue by KaelWD** [laravel/elixir#696]
I have an image referenced in a .Vue file like this:
```html
<img :src="require('./images/header.png')" alt="">
```
And another one in css in the same file:
```css
background : url('./images/banner.jpg') no-repeat;
```
If I run `gulp` it works fine and the files are copied to `public/img` with a version string at the end, but `gulp --production` fails when it's trying to uglify the output. It seems like gulp-uglify is trying to process the images, but a) they're not js files, and b) it's looking in the wrong folder for them.

Console output:
```js
λ gulp --production
[19:25:57] Using gulpfile D:\Kael\Documents\_Documents\Web\past-midnight\gulpfile.js
[19:25:57] Starting 'all'...
[19:25:57] Starting 'sass'...
[19:25:57] Finished 'sass' after 562 ms
[19:25:57] Starting 'webpack'...
{ Error
    at new JS_Parse_Error (eval at <anonymous> (D:\Kael\Documents\_Documents\Web\past-midnight\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (D:\Kael\Documents\_Documents\Web\past-midnight\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1542:11)
    at parse_error (eval at <anonymous> (D:\Kael\Documents\_Documents\Web\past-midnight\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1667:9)
    at Object.next_token [as input] (eval at <anonymous> (D:\Kael\Documents\_Documents\Web\past-midnight\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1946:9)
    at next (eval at <anonymous> (D:\Kael\Documents\_Documents\Web\past-midnight\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2075:25)
    at Object.parse (eval at <anonymous> (D:\Kael\Documents\_Documents\Web\past-midnight\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2061:15)
    at D:\Kael\Documents\_Documents\Web\past-midnight\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:71:33
    at Array.forEach (native)
    at Object.exports.minify (D:\Kael\Documents\_Documents\Web\past-midnight\node_modules\gulp-uglify\node_modules\uglify-js\tools\node.js:66:15)
    at D:\Kael\Documents\_Documents\Web\past-midnight\node_modules\gulp-uglify\minifier.js:65:22
  message: 'D:\\Kael\\Documents\\_Documents\\Web\\img\\header.fd4dec0.png: Unexpected character \'�\'',
  fileName: 'D:\\Kael\\Documents\\_Documents\\Web\\img\\header.fd4dec0.png',
  lineNumber: 1,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (D:\\Kael\\Documents\\_Documents\\Web\\past-midnight\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1534:18)\n    at js_error (eval at <anonymous> (D:\\Kael\\Documents\\_Documents\\Web\\past-midnight\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1542:11)\n    at parse_error (eval at <anonymous> (D:\\Kael\\Documents\\_Documents\\Web\\past-midnight\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1667:9)\n    at Object.next_token [as input] (eval at <anonymous> (D:\\Kael\\Documents\\_Documents\\Web\\past-midnight\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1946:9)\n    at next (eval at <anonymous> (D:\\Kael\\Documents\\_Documents\\Web\\past-midnight\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2075:25)\n    at Object.parse (eval at <anonymous> (D:\\Kael\\Documents\\_Documents\\Web\\past-midnight\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2061:15)\n    at D:\\Kael\\Documents\\_Documents\\Web\\past-midnight\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:71:33\n    at Array.forEach (native)\n    at Object.exports.minify (D:\\Kael\\Documents\\_Documents\\Web\\past-midnight\\node_modules\\gulp-uglify\\node_modules\\uglify-js\\tools\\node.js:66:15)\n    at D:\\Kael\\Documents\\_Documents\\Web\\past-midnight\\node_modules\\gulp-uglify\\minifier.js:65:22',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-uglify' }
```

I also found [this laracasts thread](https://laracasts.com/discuss/channels/elixir/laravel-webpack-vue) with the same problem, but no replies. 

<sup><sup>(yes, I'm using windows, fite me)</sup></sup>

**Comment by kevinongko** [comment]
Having this problem too, found a PR [#28](https://github.com/JeffreyWay/laravel-elixir-webpack-official/pull/28) that solve this but not merged yet,
use the following in your package json

`"laravel-elixir-webpack-official": "https://github.com/SebastianS90/laravel-elixir-webpack-official/tarball/22a3805996dfb7ca3e4137e9bdcb29232ba9f519"`

**Comment by JeffreyWay** [comment]
Merged, so closing this one. Thanks.

**Comment by SebastianS90** [comment]
@kevinongko and anyone who used the workaround: my fix got merged, please use the official version again.

`"laravel-elixir-webpack-official": "^1.0.10"`
