### ISSUE TITLE
sourcemap search on wrong place

### ISSUE THREAD

**Issue by Elbandi** [laravel/elixir#90]
I try to build [this project](https://github.com/cachethq/Cachet) with new elixir. I got this:

    [15:40:10] Using gulpfile /data/gulpfile.js
    [15:40:10] Starting 'default'...
    [15:40:10] Starting 'sass'...
    [15:40:10] Running Sass: app/assets/sass/main.scss
    [15:40:11] Finished 'default' after 405 ms
    [15:40:16] Finished 'sass' after 5.71 s
    [15:40:16] Starting 'jshint'...
    [15:40:16] Finished 'jshint' after 243 ms
    [15:40:16] Starting 'styles'...
    [15:40:16] Merging styles: ./app/assets/bower_components/ionicons/css/ionicons.css, ./app/assets/bower_components/jquery-minicolors/jquery.minicolors.css, ./public/dist/css/main.css
    fs.js:502
      return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                     ^
    Error: ENOENT, no such file or directory '/data/app/assets/bower_components/ionicons/css/main.css.map'
        at Error (native)
        at Object.fs.openSync (fs.js:502:18)
        at Object.fs.readFileSync (fs.js:354:15)
        at fromSource (/data/node_modules/laravel-elixir/node_modules/gulp-minify-css/node_modules/clean-css/lib/utils/input-source-map-tracker.js:67:31)
        at InputSourceMapStore.track (/data/node_modules/laravel-elixir/node_modules/gulp-minify-css/node_modules/clean-css/lib/utils/input-source-map-tracker.js:137:5)
        at Object.whenDone (/data/node_modules/laravel-elixir/node_modules/gulp-minify-css/node_modules/clean-css/lib/clean.js:96:44)
        at processNext (/data/node_modules/laravel-elixir/node_modules/gulp-minify-css/node_modules/clean-css/lib/imports/inliner.js:105:35)
        at importFrom (/data/node_modules/laravel-elixir/node_modules/gulp-minify-css/node_modules/clean-css/lib/imports/inliner.js:79:10)
        at ImportInliner.process (/data/node_modules/laravel-elixir/node_modules/gulp-minify-css/node_modules/clean-css/lib/imports/inliner.js:36:10)
        at /data/node_modules/laravel-elixir/node_modules/gulp-minify-css/node_modules/clean-css/lib/clean.js:71:41

I dont now why, but elixir try to search the main.css.map file in wrong place.
If i turn off the production mode on elixir.json, build is successful.

i tested with some versions:
0.10.7: works
0.12.0: not works
0.15.4: not works

**Comment by JeffreyWay** [comment]
I need better information on the exact Elixir method calls you made.
