### ISSUE TITLE
Strange error with less and sass

### ISSUE THREAD

**Issue by mabasic** [laravel/elixir#98]
I don't even know what does this mean.

```
C:\Repositories\laracasts-chrome-extension\node_modules\laravel-elixir\ingredients\commands\CompileCSS.js:14
    new Notification().error(e, options.compiler + ' Compilation Failed!');
                                ^
ReferenceError: options is not defined
    at Transform.onError (C:\Repositories\laracasts-chrome-extension\node_modules\laravel-elixir\ingredients\commands\CompileCSS.js:14:33)
    at Transform.emit (events.js:117:20)
    at onwriteError (C:\Repositories\laracasts-chrome-extension\node_modules\laravel-elixir\node_modules\gulp-less\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:250:10)
    at onwrite (C:\Repositories\laracasts-chrome-extension\node_modules\laravel-elixir\node_modules\gulp-less\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:268:5)
    at WritableState.onwrite (C:\Repositories\laracasts-chrome-extension\node_modules\laravel-elixir\node_modules\gulp-less\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:106:5)
    at afterTransform (C:\Repositories\laracasts-chrome-extension\node_modules\laravel-elixir\node_modules\gulp-less\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:104:5)
    at TransformState.afterTransform (C:\Repositories\laracasts-chrome-extension\node_modules\laravel-elixir\node_modules\gulp-less\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at C:\Repositories\laracasts-chrome-extension\node_modules\laravel-elixir\node_modules\gulp-less\index.js:48:16
    at C:\Repositories\laracasts-chrome-extension\node_modules\laravel-elixir\node_modules\gulp-less\node_modules\less\lib\less\index.js:23:26
    at Object.finish [as _finish] (C:\Repositories\laracasts-chrome-extension\node_modules\laravel-elixir\node_modules\gulp-less\node_modules\less\lib\less\parser.js:666:28)
```

**Comment by JeffreyWay** [comment]
Have you done an `npm update` lately?

**Comment by mabasic** [comment]
Hi, my bad :) I was working with old version of Elixir and then I updated it to the latest but my (custom) structure and everything else remained the same. I have managed to update everything to latest including nodejs, npm, gulp, elixir and used bower to copy bootstrap less to assets/less/bootstrap folder and now everything works.
