### ISSUE TITLE
Bug: CompileCss.js refactor throws ReferenceError for bad Sass import path

### ISSUE THREAD

**Issue by jklegseth** [laravel/elixir#99]
I've been playing with Elixir all weekend and after one of my `npm updates` I started getting a console log `ReferenceError`. I eventually tracked it down to a bad Sass partial import path.

This:
```
@import 'vendor/bower_components/scut/dist/scut';
```
should have been:
```
@import '../vendor/bower_components/scut/dist/scut';
```

Previously when this had happened I got a useful log:
```
[10:47:46] gulp-notify: [Laravel Elixir] Sass Compilation Failed!: file to import not found or unreadable: vendor/bower_components/scut/dist/scut
```

But after the update it became:

```
[10:26:43] Running Sass: resources/assets/sass/screen.scss,resources/assets/sass/email.scss,resources/assets/sass/../tablesaw/stackonly/tablesaw.stackonly.scss
/laravel5/laravel/node_modules/laravel-elixir/ingredients/commands/CompileCSS.js:14
    new Notification().error(e, options.compiler + ' Compilation Failed!');
                                ^
ReferenceError: options is not defined
    at Stream.onError (/laravel5/laravel/node_modules/laravel-elixir/ingredients/commands/CompileCSS.js:14:33)
    at Stream.emit (events.js:129:20)
    at next (/laravel5/laravel/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/map-stream/index.js:75:19)
    at /laravel5/laravel/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/map-stream/index.js:85:7
    at opts.error (/laravel5/laravel/node_modules/laravel-elixir/node_modules/gulp-sass/index.js:80:14)
    at options.error (/laravel5/laravel/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:154:7)
```

This issue was introduced as part of the refactor to CompileCss.js, commit bf76685.

**Comment by orosznyet** [comment]
I just removed "options.compiler" and it works properly.

```
var onError = function(e) {
    new Notification().error(e, ' Compilation Failed!');

    this.emit('end');
};
```

**Comment by JeffreyWay** [comment]
Do an 'npm update'. Was fixed the other day.

**Comment by ruuter** [comment]
'npm update' did not help, but reinstalling with 'npm install laravel-elixir' did the trick.
